pipeline {
    agent any

    environment {
        SERVICE_NAME = "promotion-service"
        NAMESPACE = "taller2-dev"
        IMAGE_NAME = "$SERVICE_NAME:latest"
        
        // Configuraciones de Testcontainers
        DOCKER_HOST = "unix:///var/run/docker.sock"
        TESTCONTAINERS_RYUK_DISABLED = "true"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir("services/circleguard-$SERVICE_NAME") {
                    sh "docker info"
                    sh "echo 'docker.host=unix:///var/run/docker.sock' > ~/.testcontainers.properties"
                    sh "echo 'testcontainers.host=host.docker.internal' >> ~/.testcontainers.properties"
                    sh "echo 'checks.disable=true' >> ~/.testcontainers.properties"
                    sh "export DOCKER_HOST=unix:///var/run/docker.sock && ../../gradlew clean build --no-daemon -Dtestcontainers.docker.host=unix:///var/run/docker.sock"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("services/circleguard-$SERVICE_NAME") {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                sh "cp /root/.kube/config /tmp/kubeconfig"
                sh "sed -i 's/127.0.0.1/host.docker.internal/g' /tmp/kubeconfig"
                
                withEnv(["KUBECONFIG=/tmp/kubeconfig"]) {
                    // Agregamos --insecure-skip-tls-verify para evitar el error de nombre de certificado
                    sh "kubectl apply -f k8s/dev/all-services.yaml -n $NAMESPACE --insecure-skip-tls-verify"
                    sh "kubectl rollout restart deployment/$SERVICE_NAME -n $NAMESPACE --insecure-skip-tls-verify"
                }
            }
        }
    }
}
