pipeline {
    agent any

    environment {
        SERVICE_NAME = "promotion-service"
        NAMESPACE = "taller2-dev"
        IMAGE_NAME = "$SERVICE_NAME:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir("services/circleguard-$SERVICE_NAME") {
                    sh '../../gradlew clean build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("services/circleguard-$SERVICE_NAME") {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                sh "cp /root/.kube/config /tmp/kubeconfig"
                sh "sed -i 's/127.0.0.1/host.docker.internal/g' /tmp/kubeconfig"
                
                withEnv(["KUBECONFIG=/tmp/kubeconfig"]) {
                    sh "kubectl apply -f k8s/dev/all-services.yaml -n $NAMESPACE"
                    sh "kubectl rollout restart deployment/$SERVICE_NAME -n $NAMESPACE"
                }
            }
        }
    }
}
